#!/bin/sh

#First param - path to server
#Second params - path to server data

currentDate=$(date +$VS_BACKUPS_DATE_FORMAT)
arhiveName="vs_server_backup_${currentDate}.tar.gz"

echo "Start prepared backup server..."

bash $VS_SERVER_PATH/server.sh command genbackup latest.vcbds

echo "Compress backup file..."

tar -zcvf $VS_DATA_PATH/Backups/$arhiveName $VS_DATA_PATH/Backups/latest.vcbds

echo "Cleanup old backups"

find $VS_DATA_PATH/Backups -type f -mtime +$VS_BACKUPS_AGE_LIMIT -print0 | xargs -0 rm -f

echo "Cleanup latest backup temp file"

rm -f $VS_DATA_PATH/Backups/latest.vcbds

echo "Successfully backuped"
