#!/bin/bash

tempBackupName=$VS_DATA_PATH/Backups/latest.vcbds

echo "Start backup server..."

bash vs_warning "Creating a backup of the world..."

echo "Saving world..."

bash vs_server command autosavenow

sleep 10

echo "Prepared backup..."

bash vs_server command genbackup latest.vcbds

echo "Avaiting backup..."

res=1
while [ $res -gt 0 ]
do
  backupSizeStart=$(stat -c %s $tempBackupName)
  sleep 5
  backupSizeEnd=$(stat -c %s $tempBackupName)
  if [ $backupSizeStart -lt $backupSizeEnd ]; then
        res=1
      else
        res=0
  fi
done

echo "Compress backup file..."

currentDate=$(date +$VS_BACKUPS_DATE_FORMAT)
archiveName="vs_server_backup_${currentDate}.tar.gz"
tar -zcvf $VS_DATA_PATH/Backups/$archiveName $tempBackupName

echo "Cleanup old backups"

find $VS_DATA_PATH/Backups -type f -mtime +$VS_BACKUPS_AGE_LIMIT -print0 | xargs -0 rm -f

echo "Cleanup latest backup temp file"

rm -f $tempBackupName

bash vs_warning "The backup of the world has been successfully created."

echo "Successfully backuped"
