#!/bin/sh

echo "0 0 * * * bash vs_backup" >> /home/$SERVER_USER/crontab

#echo "* * * * * echo \"CRON IS RUNNING\" >> ~/cron_debug.txt" >> /home/$SERVER_USER/crontab

chown $SERVER_USER:$SERVER_USER /home/$SERVER_USER/crontab

chmod 660 /home/$SERVER_USER/crontab

echo "Successfully updated crontab!"
