#!/bin/sh

pathToCrontab="/home/${VS_SERVER_USER}/crontab"

echo "${VS_BACKUP_PERIODICITY} bash vs_backup" >> $pathToCrontab

#echo "* * * * * echo \"CRON IS RUNNING\" >> ~/cron_debug.txt" >> $pathToCrontab

chown $VS_SERVER_USER:$VS_SERVER_USER $pathToCrontab

chmod 660 $pathToCrontab

echo "Successfully updated crontab!"
