#!/bin/sh

echo "Start installing mod..."

pathToMods=$VS_DATA_PATH/Mods

if [ -z "$1" ]; then

  read -p "Set URL_FOR_DOWNLOAD_ARCHIVE: " downloadUrl

  else

  downloadUrl=$1

fi

fileName=$(wget --server-response -q -O - "$downloadUrl" 2>&1 | grep "Content-Disposition:" | tail -1 | awk -F"filename=" '{print $2}')
fileName=$(echo $fileName | sed "s/\"//g")
fileName=$(echo $fileName | sed "s/ /_/g")
digitIndexes=$(echo $fileName | grep -aob '[[:digit:]]')
digitFirstIndex=${digitIndexes%%:*}
modName=$(echo $fileName | cut -b -$digitFirstIndex)

echo "Checking exist files..."
exsistMods=$(find $pathToMods/$modName* -print)
if [ -n "$exsistMods" ]; then
  echo "\033[1;33mATTENTION! You already have this mod installed!"
  echo "[\033[1;31m$modName\033[1;33m] Is this the correct name for the mod?"
  echo "These files will be deleted!\n$exsistMods"
  echo "CONTINUE? Press \033[1;31my\033[1;33m for continue or \033[1;31mENTER\033[1;33m / \033[1;31mn\033[1;33m for exit\033[1;31m"
  read agree
  if [ "y" != "$agree" ]; then
    echo "\033[0mYou have interrupted the installation process. EXIT!"
    exit
  fi
  echo "\033[0mRemoving..."
  # shellcheck disable=SC2115
  rm -rf $pathToMods/$modName*
fi

echo "\033[0mDownloading..."

wget -O $pathToMods/$fileName $downloadUrl

echo "Mod is successfully installed!"
