#!/bin/sh

cleanup() {
    echo "Container stopped, performing cleanup..."
    bash $VS_SERVER_PATH/server.sh stop
}

if [ ! -f $VS_SERVER_PATH/server.sh ]; then
    echo "Server runtime is missing. Download server with use 'sudo docker exec vintage_story_server bash -c \"vs_update <url_to_download_server.tar.gz>'\""
    echo "and restart container"
    sleep infinity & wait
else

    trap 'true' SIGTERM
    
    supercronic ~/crontab &
  
    bash $VS_SERVER_PATH/server.sh start
    
    sleep infinity &
    
    wait
    
    cleanup
fi
