#!/bin/bash

#First param - server download link

echo "Start updating server..."

if [ -z "$1" ]; then

  read -p "Set URL_FOR_DOWNLOAD_ARCHIVE_TAR_GZ: " downloadUrl

  else

  downloadUrl=$1

fi

if [ -f $VS_SERVER_PATH/server.sh ]; then

	echo "Stopping server..."

	bash vs_server stop

fi

echo "Cleanup server directory"

rm -rf $VS_SERVER_PATH/*

echo "Download server"

wget -O /tmp/server.tar.gz $downloadUrl

echo "Extract server"

tar -xzf /tmp/server.tar.gz -C $VS_SERVER_PATH

echo "Change grants"

chmod +x $VS_SERVER_PATH/server.sh

echo "Change path for server.sh"

sed -i -e "s/USERNAME='vintagestory'/USERNAME='$VS_SERVER_USER'/g" $VS_SERVER_PATH/server.sh
sed -i -e "s/VSPATH='\/home\/vintagestory\/server'/VSPATH='$VS_SCREENING_SERVER_PATH'/g" $VS_SERVER_PATH/server.sh
sed -i -e "s/DATAPATH='\/var\/vintagestory\/data'/DATAPATH='$VS_SCREENING_DATA_PATH'/g" $VS_SERVER_PATH/server.sh

echo "Cleanup tmp directory"

rm -rf /tmp/*

echo "Successfully updated server!"
