#!/bin/sh

#First param - server download link

if [ -z "$1" ]; then

	echo "URL params is empty. call update.sh <URL_FOR_DOWNLOAD_ARCHIVE_TAR_GZ>"
	exit

fi

echo "Start updating server..."

if [ -f $VS_SERVER_PATH/server.sh ]; then

	echo "Stopping server..."

	bash $VS_SERVER_PATH/server.sh stop

fi

echo "Cleanup server directory"

rm -rf $VS_SERVER_PATH/*

echo "Download server"

wget -O /tmp/server.tar.gz $1

echo "Extract server"

tar -xzf /tmp/server.tar.gz -C $VS_SERVER_PATH

echo "Change grants"

chmod +x $VS_SERVER_PATH/server.sh

echo "Change path for server.sh"

sed -i -e "s/USERNAME='vintagestory'/USERNAME='$VS_SERVER_USER'/g" $VS_SERVER_PATH/server.sh
sed -i -e "s/VSPATH='\/home\/vintagestory\/server'/VSPATH='$VS_SCREENING_SERVER_PATH'/g" $VS_SERVER_PATH/server.sh
sed -i -e "s/DATAPATH='\/var\/vintagestory\/data'/DATAPATH='$VS_SCREENING_DATA_PATH'/g" $VS_SERVER_PATH/server.sh

echo "Cleanup tmp directory"

rm -rf /tmp/*

echo "Successfully updated server!"
